### PR TITLE
Add CMD+SHIFT+S menu shortcut for Save As

### PR DESCRIPTION
**Pull request by weavermedia**

### CODE REVIEW

**Comment by weavermedia** [comment]
I've been using Edisyn to create lots of variation patches for the FB-01. Having a keyboard shortcut for Save Add will be very helpful! 😀

**Comment by eclab** [comment]
I'm confused -- Save As *has* a shortcut already, and it's command-shift-S.  It's had it for many years.  Any idea what's going on?

**Comment by weavermedia** [comment]
Strange. I'm running Edisyn 31 on macOS 10.14.6 and it doesn't look like that shortcut is registered. There's no indication of the shortcut in the menu (image below) and when I hit CMD+SHIFT+S nothing happens.

I looked through the Synth.java file and couldn't see anywhere mentioning  `saveAs` so I added it.

CleanShot 2022-10-11 at 08 55 59

**Comment by eclab** [comment]
You're right, it's missing in the code!  It's on my menu for another reason, so I had missed it.

I just committed fixes, and they'll appear in the next binary.

Sean

**Pull request closed without merging**
