### PR TITLE
Some more dstation fixes

### PR DESCRIPTION
**Pull request by cpacejo**
Hi, a few more fixes for the D Station.  Also a build fix for an unrelated synth.

### CODE REVIEW

**Comment by eclab** [comment]
The Kawai K1 has build issues because it's the last synth I'm preparing for the librarian. So I'll have a different route there.

**Comment by cpacejo** [comment]
Ah I figured something was up there.  Want me to drop that commit?

**Comment by eclab** [comment]
Drop the K1. But tell me more about the Drumstation changes you're making.

**Comment by cpacejo** [comment]
Done.

"remove OC drum type" --> this is dead code, there are no drums named as such in the class (or in the actual Drum Station for that matter).

"fix naming conflict of Hand Clap and High Conga" --> both Hand Clap and High Conga were referred to as "HC" in the class, which resulted in changes to one being reflected in the other, and vice-versa.  This renames all Hand Clap drums to "CP", which resolves the conflict.

"fix bank select order" --> the numbering of drums for the "bank select" configuration is incorrect, causing D Station sysex files to contain the incorrect values here.  (Namely the 808 and 909 drums are swapped.)  This just swaps their order, without changing the order of the drums in the UI panels.  I've confirmed this change against an actual D Station.

**Comment by cpacejo** [comment]
Side note -- it may be helpful to add a Git tag when making a release (e.g. v29 at commit b49d1550) so it's easy for anyone building from source to get a clean build.  (I couldn't find that commit at first, hence why I bumped into the Kawai build issue.)

**Comment by eclab** [comment]
I wish!  I am, believe it or not, using svn via a bridge.

**Comment by eclab** [comment]
So I'm looking over the changes.  OC is dead, can be removed.  Hand Clap seems correct, should be changed.  But I'm concerned about the bank order.    Understand that the sysex document is one I reverse engineered a while ago and I was pretty sure back then that the bank ordering (Table 6) did in fact have the 808 first.  MidiQuest seems to have 808 first too.  It'll take a while for me to verify this as I'm knee-deep in librarian-building.  In the meantime, can you present anything convincing enough to make the change preemptively?  If so I'd trust you.

**Comment by cpacejo** [comment]
I dumped patch 0 ("Classic TR909 V1") from my own Drum Station.  Without the change, Edisyn lists banks A through D as:

- 808 Low Conga
- 909 Closed High Hat
- 909 Ride Cymbal
- 909 Low Tom

Which do not match with the banks as reported by the Drum Station itself:

- 808 bd (Bass Drum)
- 808 C2 (Mid Conga)
- 808 CL (Claves)
- 808 Cb (Cowbell)

However, with the change, Edisyn correctly reports these banks as:

- 808 Bass Drum
- 808 Mid Conga
- 808 Claves
- 808 Cowbell

I tested this with several other built-in patches as well, and also by loading my own patch which I created with Edisyn, for which the banks did not translate correctly without this change (and the wrong sounds came out), but do translate correctly with them (and the correct sounds came out).

If you own a Drum Station you can confirm the above for yourself.

I can't speak to why MidiQuest reversed these.  However, some of the drum names line up when in the incorrect order, just with 808 swapped for 909.  And the order as listed in the manual lists the 808 drums first.  It would be an easy mistake to make, to assume the drum numbering follows the order listed in the manual, and check the names (but not the kit) of only the first few drums.

**Comment by eclab** [comment]
All right, let's do it.

**Comment by cpacejo** [comment]
Cool, thanks!

**Pull request merged**
